# Generated by Django 5.1.3 on 2024-12-01 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meseros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meseros',
            name='dni',
            field=models.CharField(default='00000000', max_length=8),
        ),
    ]
